config/routes.rb
Rails.application.routes.draw do
  get 'articles', to: "articles#index"
  get 'articles/new', to: "articles#new"
  post 'articles', to: "articles#create"
  get 'articles/:id', to: "articles#show", as: :article
  get 'articles/:id/edit', to: "articles#edit", as: :edit
  patch 'articles/:id', to: "articles#update"
  delete 'articles/:id', to: "articles#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to "➕ Add a new article", articles_new_path %>
<ul class="inline"><% @articles.each do |article| %>
  <h3><%= link_to article.title, article_path(article.id) %></h3>
  <p><%= article.content %></p>
<% end %>
</ul>

app/views/articles/new.html.erb
<h1>Add a new article</h1>
<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to "↩️ Back to list", articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %> <%= link_to "🖊", edit_path %> <%= link_to "🗑", article_path(@article),
      method: :delete,
      data: { confirm: "Are you sure?" } %></h1>

<p><%= @article.content %></p>

<%= link_to "↩️ Back to list", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous"
  </head>

  <body>
    <%= yield %>
  </body>
</html>